version: '3.9'

services:

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vote-api
    ports:
      - "5432:5432"

  vote-api:
    build: ./vote-api
    ports:
      - "8080:8080"
    environment:
      - PG_URL="postgresql://user:password@5432/vote-api?sslmode=disable"

  web-client:
    build: ./web-client
    ports:
      - "3000:3000"
    environment:
      - VOTE_API_BASE_URL=http://vote-api:8080

  docs:
    build: ./docs
    ports:
      - "80:80"