version: '3.9'

services:

  vote-api:
    build:
      context: ./vote-api
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PG_URL="postgresql://user:password@ep-hidden-mountain-a53rwzo1.us-east-2.aws.neon.tech/neondb?sslmode=require"

  web-client:
    depends_on:
      - vote-api
    build:
      context: ./web-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VOTE_API_BASE_URL=http://vote-api:8080

  docs:
    build:
      context: ./docs
      dockerfile: Dockerfile
    ports:
      - "3001:80"