version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./apps/postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vote-api
    networks:
      - tp-final-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d vote-api" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  vote-api:
    build:
      context: ./vote-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - tp-final-network
    environment:
      - PG_URL=postgresql://user:password@postgres:5432/vote-api?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  web-client:
    depends_on:
      - vote-api
    build:
      context: ./web-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - tp-final-network
    environment:
      - VOTE_API_BASE_URL=http://vote-api:8080

  docs:
    build:
      context: ./docs
      dockerfile: Dockerfile
    ports:
      - "80:80"

networks:
  tp-final-network:
    driver: bridge