name: Continuous Integration Pipeline

on:
  push:
    branches:
      - "main"
      - "develop/*"
  pull_request:
    branches:
      - "main"

jobs:

  api-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - run: |
          cd vote-api
          go mod tidy
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ./bin v1.63.4
          ./bin/golangci-lint run

  api-format:
    runs-on: ubuntu-latest
    needs: api-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - run: |
          cd vote-api
          go fmt ./...

  api-tests:
    runs-on: ubuntu-latest
    needs: api-format
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - run: |
          cd vote-api
          go test ./...

  api-build:
    runs-on: ubuntu-latest
    needs: api-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - run: |
          cd vote-api
          go build