name: Continuous Integration Pipeline

on:
  push:
    branches:
      - "main"
      - "develop/*"
  pull_request:
    branches:
      - "main"

jobs:

  api-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - run: |
          cd vote-api
          go mod tidy
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ./bin v1.63.4
          ./bin/golangci-lint run

  api-format:
    runs-on: ubuntu-latest
    needs: api-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - run: |
          cd vote-api
          go fmt ./...

  api-tests:
    runs-on: ubuntu-latest
    needs: api-format
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - run: |
          cd vote-api
          go test ./...

  api-build:
    runs-on: ubuntu-latest
    needs: api-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - run: |
          cd vote-api
          go build
          
  push_api_to_registry:
    name: push docker image to hub
    needs: api-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.USERNAME_CHEVALIER}}
          password: ${{secrets.PASSWORD_CHEVALIER}}

      - name: Build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: ./vote-api
          push: true
          tags: chevalier/vote-api:latest